development:
  adapter: postgresql
  database: my_database_development_xx
  username: postgres
  password: vaibhavgeek 
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: my_database_test_xx
  username: postgres
  password: vaibhavgeek 
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: my_database_production_xx
  username: postgres
  password: vaibhavgeek
  pool: 5
  timeout: 5000